# Generated by Django 3.0.3 on 2020-02-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logged_in',
        ),
    ]
