# Generated by Django 3.0.4 on 2020-03-19 09:25

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default-profile-image.png', upload_to=account.models.avatar_file_path),
        ),
    ]
