# Generated by Django 3.0.4 on 2020-03-20 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile__default_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='_default_avatar',
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=12)),
                ('valid_until', models.DateTimeField(blank=True)),
                ('login_attempts', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
