# Generated by Django 3.0.4 on 2020-03-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200320_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
