# Generated by Django 3.0.4 on 2020-03-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200320_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='token_2',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
