# Generated by Django 3.0.4 on 2020-03-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_security_token_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='share_level',
            field=models.CharField(choices=[('read', 'Read only'), ('complete', 'Complete tasks'), ('all', 'Edit items')], default='read', max_length=10),
        ),
    ]
