# Generated by Django 3.0.4 on 2020-03-26 10:32

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_share_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/default-profile-image.png', upload_to=account.models.avatar_file_path),
        ),
    ]
