# Generated by Django 3.0.4 on 2020-03-26 12:23

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200326_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default-profile-image.png', upload_to=account.models.avatar_file_path),
        ),
    ]
