# Generated by Django 3.0.4 on 2020-03-06 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0006_auto_20200305_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
