# Generated by Django 3.1.3 on 2020-11-18 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0009_sharedshoppinglist_access_level'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Item',
                    fields=[
                        ('id',
                         models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted', models.DateTimeField(blank=True, default=None,
                                                         help_text='The date and time when the object was deleted',
                                                         null=True, verbose_name='date of deletion')),
                        ('name', models.CharField(db_index=True, max_length=200, verbose_name='item name')),
                        ('code', models.CharField(blank=True, max_length=20, verbose_name='item code')),
                        ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True,
                                                      validators=[django.core.validators.MinValueValidator(0)])),
                        ('creation_date', models.DateTimeField(auto_now_add=True)),
                        ('tags', models.ManyToManyField(blank=True, to='shopping_list.Category')),
                        ('user',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'item',
                        'ordering': ('id',),
                    },
                ),
            ],
            # Referencing an existing table which was moved from the shopping_lists module to the items module,
            # creation not required and is faked
            database_operations=[]
        )
    ]
